version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
    - image: circleci/node:lts-jessie-browsers-legacy

jobs:
    test:
        <<: *defaults
        steps:
        - checkout

        - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run:
              name: Print version
              command: |
                  export VERSION=`cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]'`
                  echo Version: $VERSION
        - run: yarn
        - run: yarn add global snyk
        - run:
              name: Build prod
              command: npm run webpack:prod
        - run:
              name: Run tests
              command: npm test

        - save_cache:
              paths:
              - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}

        - persist_to_workspace:
              root: ~/repo
              paths:
                  - dist
                  - target
                  - .
    docker-build:
        docker:
        - image: docker
        working_directory: ~/repo
        steps:
        - attach_workspace:
              at: ~/repo
        - setup_remote_docker:
              docker_layer_caching: true
        # build and push Docker image to dockerhub.
        - run: |
              export VERSION=`cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]'`
              docker build -t grindrodbank/spoon-ui:$VERSION -f Dockerfile-jenkins .
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag grindrodbank/spoon-ui:$VERSION grindrodbank/spoon-ui:latest
              docker push grindrodbank/spoon-ui:latest
              docker push grindrodbank/spoon-ui:$VERSION
    deploy:
        <<: *defaults
        steps:
        - attach_workspace:
              at: ~/repo
        - run: yarn
        - run:
              name: update-npm
              command: 'sudo npm install -g npm@latest'
        - run:
              name: install-snyk
              command: 'sudo npm install -g snyk'
        - run:
              name: Build
              command: npm run lib
        - run:
              name: Authenticate with registry
              command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
        - run:
              name: Publish package
              command: npm publish dist/
    vulnerability-test:
        <<: *defaults
        steps:
        - checkout 
        - run:
              name: update-npm
              command: 'sudo npm install -g npm@latest'
        - run:
              name: install-snyk
              command: 'sudo npm install -g snyk'     
        - run: # run snyk help - test snyk is installed and working
              name: snyk-help
              command: snyk --help
        - run: # run snyk auth - authenticate snyk use environment variables to add token
              name: snyk auth
              command: snyk auth $SNYK_TOKEN
        - run: # run snyk test - run snyk test
             name: snyk test
             command: snyk test -d
workflows:
    version: 2
    build-commit:
        jobs:
        - test
        - vulnerability-test
        - docker-build:
              requires:
              - test
#              - vulnerability-test
              filters:
                  tags:
                      only: /^v*.*.*/
                  branches:
                      only: master
        - deploy:
              requires:
              - test
              - vulnerability-test
              filters:
                  tags:
                      only: /^v*.*.*/
                  branches:
                      only: master
